#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

# unfortunately docker-compose _requires_ a specified env_file to be present on
# disk. we shouldn't add these into git however as it can result in deployment
# secrets accidentally getting pushed into the git repo.
touch store-api-server/.env
touch admin-api-server/.env

docker-compose build
