#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -e -u

sigErrFile=`mktemp`
rm $sigErrFile
echo "building stm-lib.."
(
    trap "echo 'stm-lib build failed' >> $sigErrFile" ERR

    cd stm-lib
    yarn install --frozen-lockfile --link-duplicates
    yarn build
) &
echo "building api-lib.."
(
    trap "echo 'api-lib build failed' >> $sigErrFile" ERR

    cd ../lib/api-lib
    yarn install --frozen-lockfile --link-duplicates
    yarn build
) &
wait
[ -f $sigErrFile ] && {
    cat $sigErrFile
    rm $sigErrFile
    exit 1
}

links=`ls -l node_modules | grep ^l`
echo "$links" | grep -q 'kanvas-stm-lib ->' || {
    echo "linking stm-lib.."
    (
        cd stm-lib
        yarn link $YARN_LINK_ARGS 2>/dev/null
    )
    yarn link $YARN_LINK_ARGS kanvas-stm-lib
}
echo "$links" | grep -q 'kanvas-api-lib ->' || {
    echo "linking api-lib.."
    (
        cd ../lib/api-lib
        yarn link $YARN_LINK_ARGS 2>/dev/null
    )
    yarn link $YARN_LINK_ARGS kanvas-api-lib
}
