#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -u

echo "building stm-lib.."
(
    cd stm-lib
    yarn build
) &
echo "building api-lib.."
(
    cd ../lib/api-lib
    yarn build
) &
wait

links=`ls -l node_modules | grep ^l`
echo "$links" | grep --silent 'kanvas-stm-lib ->' || {
    echo "linking stm-lib.."
    (
        cd stm-lib
        yarn link 2>/dev/null
    )
    yarn link kanvas-stm-lib
}
echo "$links" | grep --silent 'kanvas-api-lib ->' || {
    echo "linking api-lib.."
    (
        cd ../lib/api-lib
        yarn link 2>/dev/null
    )
    yarn link kanvas-api-lib
}
