#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

INIT_QUEPASA=false script/migrate

if [[ "`psql -c \"select count(1) from kanvas_user\" -tA`" == "0" ]]; then
    yarn seed
    script/setup-replication-sub
fi

node dist/src/main.js