#!/usr/bin/env bash

INIT_QUEPASA=false script/migrate

if [[ "`psql -c \"select count(1) from kanvas_user\" -tA`" == "0" ]]; then
    yarn seed
    script/setup-replication-sub
fi

node dist/src/main.js