#!/usr/bin/env bash
cd $(git rev-parse --show-toplevel)/admin-api-server

trap "kill 0" EXIT

[ -z $PGHOST ] && export PGHOST=localhost
[ -z $PGPORT ] && export PGPORT=5433
[ -z $PGUSER ] && export PGUSER=dev_user
[ -z $PGPASSWORD ] && export PGPASSWORD=dev_password
[ -z $PGDATABASE ] && export PGDATABASE=dev_database

(
    ./script/wait-db
    ./script/migrate up
) &

echo Starting Admin DB at $PGUSER@$PGHOST:$PGPORT/$PGDATABASE

[ -z $DOCKER_ARGS ] && export DOCKER_ARGS='-t'
docker run $DOCKER_ARGS \
    -p $PGPORT:5432 \
    -e POSTGRES_USER=$PGUSER \
    -e POSTGRES_PASSWORD=$PGPASSWORD \
    -e POSTGRES_DB=$PGDATABASE \
    postgres "$@"
