#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

[ -z $PGHOST ] && export PGHOST=localhost
[ -z $PGPORT ] && export PGPORT=5433
[ -z $PGUSER ] && export PGUSER=dev_user
[ -z $PGPASSWORD ] && export PGPASSWORD=dev_password
[ -z $PGDATABASE ] && export PGDATABASE=dev_database
[ -z $PGHOST ] && export PGHOST=localhost

(
    if [[ ${DBSETUP_LOG} == "quiet" ]]; then
        exec 1>/dev/null
        exec 2>/dev/null
    fi

    ./script/wait-db
    ./script/migrate up
) &

[ -z $DOCKER_ARGS ] && export DOCKER_ARGS="-t"
docker run $DOCKER_ARGS \
    -p $PGPORT:5432 \
    -e POSTGRES_USER=$PGUSER \
    -e POSTGRES_PASSWORD=$PGPASSWORD \
    -e POSTGRES_DB=$PGDATABASE \
    postgres:13 "$@"
