#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

[ -z $PGHOST ] && export PGHOST=localhost
[ -z $PGPORT ] && export PGPORT=5433
[ -z $PGUSER ] && export PGUSER=dev_user
[ -z $PGPASSWORD ] && export PGPASSWORD=dev_password
[ -z $PGDATABASE ] && export PGDATABASE=dev_database


./script/shmig -t postgresql -d postgres://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE up || exit 1
