#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

PGDATABASE=store_replication psql -c 'DROP SUBSCRIPTION IF EXISTS store_sub;' || {
  # drop subscription may fail if it couldn't reach the store-db for some reason
  # , or if the replication slot was already cleaned up in a previous
  # _partially failed_ drop subscription action
  # (it tries to reach the store-db to cleanup resources)
  PGDATABASE=store_replication psql -c '
    ALTER SUBSCRIPTION store_sub DISABLE;
    ALTER SUBSCRIPTION store_sub SET (slot_name = NONE);
    DROP SUBSCRIPTION store_sub;
  '
}

PGDATABASE=store_replication psql -c '
BEGIN;

DROP SCHEMA IF EXISTS peppermint CASCADE;
DROP SCHEMA IF EXISTS onchain_kanvas CASCADE;

-- dropping the following set of schemas in case they exist, they might if the
-- admin quepasa was started with the same que pasa config as the store quepasa
DROP SCHEMA IF EXISTS paypoint CASCADE;
DROP SCHEMA IF EXISTS token_gate CASCADE;

DROP SCHEMA IF EXISTS que_pasa CASCADE;
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

COMMIT;' || exit 1

./setup-replication-sub
