#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

PGDATABASE=store_replication psql -c '
BEGIN;

DROP SCHEMA IF EXISTS onchain_kanvas CASCADE;

-- dropping the following set of schemas in case they exist, they might if the
-- admin quepasa was started with the same que pasa config as the store quepasa
DROP SCHEMA IF EXISTS paypoint CASCADE;
DROP SCHEMA IF EXISTS token_gate CASCADE;

DROP SCHEMA IF EXISTS que_pasa CASCADE;
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

COMMIT;' || exit 1
PGDATABASE=store_replication psql -c 'DROP SUBSCRIPTION store_sub'

./setup-replication-sub
