#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

# must copy over table, enum definitions, etc first. Otherwise the
# subscription will not work (it will not bring over these definitions, unfortunately)

store_schema_file=`mktemp`
PGPASSWORD=$STORE_PGPASSWORD pg_dump --host=$STORE_PGHOST --port=$STORE_PGPORT --dbname=$STORE_PGDATABASE --username=$STORE_PGUSER --schema-only -T public.claims --format c --no-privileges --no-owner > $store_schema_file

PGDATABASE=store_replication psql -c "
  CREATE SCHEMA IF NOT EXISTS peppermint;
" || exit 1

pg_restore --no-publications --schema=public --schema=peppermint --host=$PGHOST --port=$PGPORT --username=$PGUSER --schema-only --no-owner --clean --if-exists --dbname=store_replication < $store_schema_file || exit 1

PGDATABASE=store_replication psql -c "
    CREATE SUBSCRIPTION store_sub
    CONNECTION 'host=$STORE_PGHOST port=$STORE_PGPORT dbname=$STORE_PGDATABASE user=$STORE_PGUSER password=$STORE_PGPASSWORD'
    PUBLICATION store_pub;
" || exit 1

./db_procedures
