#!/usr/bin/env bash

INIT_QUEPASA=false script/migrate

if [[ '`psql -c \"select count(1) from kanvas_user\" -tA`' != '0' ]]; then 
    psql -c 'ALTER USER replication_user REPLICATION'
    psql < script/populate-stagingdb.sql
fi

node dist/src/main.js