#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -e -u

INIT_QUEPASA=false script/migrate

if [[ '`psql -c \"select count(1) from nft_category\" -tA`' == '0' ]]; then
    psql < script/populate-stagingdb.sql
fi

node dist/src/main.js
