#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

PEPPERMINT_VERSION=ee538be4d156ffb456107587eb71f14671afb1c7
[ -z $PGPORT ] && export PGPORT=5432
[ -z $PGPASSWORD ] && export PGPASSWORD=dev_password
[ -z $PGUSER ] && export PGUSER=dev_user
[ -z $PGDATABASE ] && export PGDATABASE=dev_database
[ -z $PGHOST ] && export PGHOST=localhost

(
    if [[ ${DBSETUP_LOG} == "quiet" ]]; then
        exec 1>/dev/null
        exec 2>/dev/null
    fi

    ./script/migrate || exit 1

    psql < script/populate-testdb.sql
) &

[ -z $DOCKER_ARGS ] && export DOCKER_ARGS='-t'

docker run ${DOCKER_ARGS} \
    -p $PGPORT:5432 \
    -e POSTGRES_PASSWORD=$PGPASSWORD \
    -e POSTGRES_USER=$PGUSER \
    -e POSTGRES_DB=$PGDATABASE \
    postgres \
        -c wal_level=logical \
        "$@"
