#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

PEPPERMINT_VERSION=ee538be4d156ffb456107587eb71f14671afb1c7
QUEPASA_VERSION=${QUEPASA_VERSION:-'1.2.6'}

if [[ ${INIT_QUEPASA:-'true'} == "true" ]]; then
    # to set up the database schema of onchain_kanvas:
    source $SCRIPT_DIR/../../config/.env-kanvas
    export DATABASE_URL="host=$PGHOST dbname=$PGDATABASE user=$PGUSER password=$PGPASSWORD port=$PGPORT"

    docker run \
        -v $SCRIPT_DIR/../../config:/config \
        --network host \
        -e NODE_URL=$NODE_URL \
        -e DATABASE_URL="$DATABASE_URL" \
        ghcr.io/tzconnectberlin/que-pasa:$QUEPASA_VERSION \
        --contract-settings /config/kanvas.yaml --only-migrate \
        || exit 1
fi

if [[ ${INIT_PEPPERMINT:-'true'} == "true" ]]; then
    curl "https://raw.githubusercontent.com/tzConnectBerlin/peppermint/${PEPPERMINT_VERSION}/database/schema.sql" 2>/dev/null | psql || exit 1
fi

psql < ../lib/tezpay/server/database/schema.sql || exit 1

./script/shmig -t postgresql -d postgres://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE up || exit 1
psql -v ON_ERROR_STOP=1 <<EOF
BEGIN;

`cat db_procedures/*`

COMMIT;
EOF

psql -v ON_ERROR_STOP=1 <<EOF
CREATE INDEX IF NOT EXISTS onchain_transfer_entry_idx ON onchain_kanvas."entry.transfer.noname.txs"(token_id, to_);
CREATE INDEX IF NOT EXISTS onchain_mint_entry_idx ON onchain_kanvas."entry.transfer.noname.txs"(token_id, owner);
CREATE INDEX IF NOT EXISTS onchain_ledger_address_idx ON onchain_kanvas."storage.ledger_live"(idx_assets_address);
CREATE INDEX IF NOT EXISTS onchain_txs_hash_idx ON que_pasa.txs(operation_hash);
EOF
