#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

PEPPERMINT_VERSION=ee538be4d156ffb456107587eb71f14671afb1c7
QUEPASA_VERSION=1.2.0

./script/wait-db

if [[ ${INIT_QUEPASA:-'true'} == "true" ]]; then
    # to set up the database schema of onchain_kanvas:
    source $SCRIPT_DIR/../../config/.env-kanvas
    export DATABASE_URL="host=$PGHOST dbname=$PGDATABASE user=$PGUSER password=$PGPASSWORD port=$PGPORT"

    docker run \
        -v $SCRIPT_DIR/../../config:/config \
        --network host \
        -e NODE_URL=$NODE_URL \
        -e DATABASE_URL="$DATABASE_URL" \
        ghcr.io/tzconnectberlin/que-pasa:$QUEPASA_VERSION \
        --contract-settings /config/kanvas.yaml --only-migrate \
        || exit 1 # >/dev/null 2>&1 || exit 1
else
    ./script/wait-db 'select 1 from que_pasa.levels'
fi

curl "https://raw.githubusercontent.com/tzConnectBerlin/peppermint/${PEPPERMINT_VERSION}/database/schema.sql" 2>/dev/null | psql || exit 1

./script/shmig -t postgresql -d postgres://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE up || exit 1
