#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

if [ -z $COUNTRY_IP_DEFINITIONS_FILE ]; then
    echo "warning: cannot fill country,ip_country tables for VAT, COUNTRY_IP_DEFINITIONS_FILE env var not set"
    exit 1
fi

echo $COUNTRY_IP_DEFINITIONS_FILE
cat $COUNTRY_IP_DEFINITIONS_FILE

psql -1 < $COUNTRY_IP_DEFINITIONS_FILE
psql -c "$(cat<<EOF

BEGIN;

INSERT INTO country (country_short, country_long)
SELECT DISTINCT
    countryshort,
    countrylong
FROM ipcountry;

INSERT INTO ip_country (ip_from, ip_to, country_id)
SELECT
    ipfrom,
    ipto,
    country.id
FROM ipcountry
JOIN country
  ON ipcountry.countryshort = country.country_short;

-- DROP TABLE ipcountry;

COMMIT;

EOF
)"
