#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -x

if [ -z $COUNTRY_IP_DEFINITIONS_FILE ]; then
    echo "warning: cannot fill country,ip_country tables for VAT, COUNTRY_IP_DEFINITIONS_FILE env var not set"
    exit 1
fi

echo $COUNTRY_IP_DEFINITIONS_FILE
cat $COUNTRY_IP_DEFINITIONS_FILE

function psql {
  gcloud beta sql connect mu-nft-webshop-db-ed7f8c78 --user=default
}

psql -1 < $COUNTRY_IP_DEFINITIONS_FILE
psql -c "$(cat<<EOF

BEGIN;

DELETE FROM ip_country;
DELETE FROM country;

INSERT INTO country (country_short, country_long)
SELECT DISTINCT
    countryshort,
    countrylong
FROM ipcountry;

INSERT INTO ip_country (ip_from, ip_to, country_id)
SELECT
    ipfrom,
    ipto,
    country.id
FROM ipcountry
JOIN country
  ON ipcountry.countryshort = country.country_short;

DROP TABLE ipcountry;

INSERT INTO vat (percentage)
VALUES (20)
ON CONFLICT DO NOTHING;

UPDATE country
SET vat_id = (SELECT id FROM vat WHERE percentage = 20)
WHERE country_short IN ('GB');

COMMIT;

EOF
)"
