#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

mkdir -p test/coverage
jest "$@" --coverage | tee test/coverage/summary.txt || exit 1
sed -n '/^-----/,$p' test/coverage/summary.txt > test/coverage/summary_.txt
head -n 4 test/coverage/summary_.txt | awk -F '|' '{print $2 $3 $4 $5}'
sed 's/^/\n/' test/coverage/summary_.txt > test/coverage/summary.txt
rm test/coverage/summary_.txt
