-- Migration: nft_4columns
-- Created at: 2021-11-10 10:40:07
-- ====  UP  ====

BEGIN;

ALTER TABLE nft ADD COLUMN price NUMERIC;
ALTER TABLE nft ADD COLUMN editions_size INTEGER;
ALTER TABLE nft ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE nft ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();

CREATE INDEX ON nft(updated_at);
CREATE INDEX ON nft(price);

COMMIT;

-- ==== DOWN ====

BEGIN;

ALTER TABLE nft DROP COLUMN price;
ALTER TABLE nft DROP COLUMN editions_size;
ALTER TABLE nft DROP COLUMN created_at;
ALTER TABLE nft DROP COLUMN updated_at;

COMMIT;
